namespace Mimer
{
    internal static class MimeRepository
    {
        private const string DefaultMimeType = "application/octet-stream";

        // TODO: [snowinmars] to xml
        // see
        // * https://en.wikipedia.org/wiki/List_of_file_signatures
        // * https://www.garykessler.net/library/file_sigs.html
        internal static readonly Fingerprint[] Fingerprints = new[]
        {
            new Fingerprint("5249 4646", "5741 5645", "audio/vnd.wave", DetectedMimeType.Wav),
            new Fingerprint("5249 4646", string.Empty, DefaultMimeType, DetectedMimeType.Riff),
            new Fingerprint("a1b2 c3d4", string.Empty, DefaultMimeType, DetectedMimeType.Pcap),
            new Fingerprint("d4c3 b2a1", string.Empty, DefaultMimeType, DetectedMimeType.Pcap),
            new Fingerprint("0a0d0d0a", string.Empty, DefaultMimeType, DetectedMimeType.Pcapng),
            new Fingerprint("edab eedb", string.Empty, DefaultMimeType, DetectedMimeType.Rpm),
            new Fingerprint("5351 4c69 7465 2066 6f72 6d61 7420 3300",
                            string.Empty,
                            DefaultMimeType,
                            DetectedMimeType.SqlLiteDb),
            new Fingerprint("5350 3031", string.Empty, DefaultMimeType, DetectedMimeType.Bin),
            new Fingerprint(new string('0', 48), string.Empty, DefaultMimeType, DetectedMimeType.Pdb),
            new Fingerprint("0000 0100", string.Empty, "image/vnd.microsoft.icon", DetectedMimeType.Ico),
            new Fingerprint("6674 7970 3367", string.Empty, "video/3gpp", DetectedMimeType._3gp),
            new Fingerprint("1f9d", string.Empty, "application/x-tar", DetectedMimeType.TarZ),
            new Fingerprint("1fa0", string.Empty, "application/x-tar", DetectedMimeType.TarZ),
            new Fingerprint("425a 68", string.Empty, "application/zip", DetectedMimeType.Bzip),
            new Fingerprint("4749 4638 3761", string.Empty, "image/gif", DetectedMimeType.Gif),
            new Fingerprint("4749 4638 3961", string.Empty, "image/gif", DetectedMimeType.Gif),
            new Fingerprint("4949 2a00", string.Empty, "image/tiff", DetectedMimeType.Tif),
            new Fingerprint("4d4d 002a", string.Empty, "image/tiff", DetectedMimeType.Tif),
            new Fingerprint("4250 47fb", string.Empty, DefaultMimeType, DetectedMimeType.Bpg),
            new Fingerprint("ffd8 ffd8", string.Empty, "image/jpeg", DetectedMimeType.Jpg),
            new Fingerprint("ffd8 ffe0 0010 4a46 4946 0001", string.Empty, "image/jpeg", DetectedMimeType.Jpg),
            new Fingerprint("ffd8 ffee", string.Empty, "image/jpeg", DetectedMimeType.Jpg),
            new Fingerprint("ffd8 ffe1", "4578 6966 0000", "image/jpeg", DetectedMimeType.Jpg),
            new Fingerprint("4d5a", string.Empty, DefaultMimeType, DetectedMimeType.DllOrExe),
            new Fingerprint("504b 0304", string.Empty, "application/zip", DetectedMimeType.Zip),
            new Fingerprint("054b 0506", string.Empty, "application/zip", DetectedMimeType.Zip),
            new Fingerprint("504b 0708", string.Empty, "application/zip", DetectedMimeType.Zip),
            new Fingerprint("5261 7221 1a07 00", string.Empty, "application/x-rar-compressed", DetectedMimeType.Rar),
            new Fingerprint("5261 7221 1a07 0100", string.Empty, "application/x-rar-compressed", DetectedMimeType.Rar),
            new Fingerprint("7f45 4c46", string.Empty, DefaultMimeType, DetectedMimeType.Elf),
            new Fingerprint("8950 4e47 0d0a 1a0a", string.Empty, "image/png", DetectedMimeType.Png),
            new Fingerprint("cafe babe", string.Empty, DefaultMimeType, DetectedMimeType.JavaClass),
            new Fingerprint("2521 5053", string.Empty, "application/postscript", DetectedMimeType.PostScript),
            new Fingerprint("2550 4446 2d", string.Empty, "application/pdf", DetectedMimeType.Pdf),
            new Fingerprint("3026 b275 8e66 cf11 a6d9 00aa 0062 ce6c",
                            string.Empty,
                            DefaultMimeType,
                            DetectedMimeType.Asf),
            new Fingerprint("2453 4449 3030 3031", string.Empty, DefaultMimeType, DetectedMimeType.MicrosoftSdi),
            new Fingerprint("4f67 6753", string.Empty, "audio/ogg", DetectedMimeType.Ogg),
            new Fingerprint("3842 5053", string.Empty, DefaultMimeType, DetectedMimeType.Photoshop),
            new Fingerprint("5249 4646", "4156 4920", DefaultMimeType, DetectedMimeType.Avi),
            new Fingerprint("fffb", string.Empty, "audio/mpeg", DetectedMimeType.Mp3),
            new Fingerprint("424d", string.Empty, DefaultMimeType, DetectedMimeType.Bmp),
            new Fingerprint("4344 3030 31", string.Empty, DefaultMimeType, DetectedMimeType.Iso),
            new Fingerprint("664c 6143", string.Empty, "audio/ogg", DetectedMimeType.Flac),
            new Fingerprint("4d54 6864", string.Empty, DefaultMimeType, DetectedMimeType.Midi),
            new Fingerprint("d0cf 11e0 a1b1 1ae1", string.Empty, DefaultMimeType, DetectedMimeType.MicrosoftOffice),
            new Fingerprint("6465 780a 3033 3500", string.Empty, DefaultMimeType, DetectedMimeType.Dex),
            new Fingerprint("4b44 4d", string.Empty, DefaultMimeType, DetectedMimeType.Vmdk),
            new Fingerprint("4372 3234", string.Empty, DefaultMimeType, DetectedMimeType.Crx),
            new Fingerprint("4147 4433", string.Empty, DefaultMimeType, DetectedMimeType.Fh8),
            new Fingerprint("0507 0000 424F 424F 0507 0000 0000 0000 0000 0000 0001",
                            string.Empty,
                            DefaultMimeType,
                            DetectedMimeType.AppleWorks5),
            new Fingerprint("0607 E100 424F 424F 0607 E100 0000 0000 0000 0000 0001",
                            string.Empty,
                            DefaultMimeType,
                            DetectedMimeType.AppleWorks6),
            new Fingerprint("7861 7221", string.Empty, DefaultMimeType, DetectedMimeType.Xar),
            new Fingerprint("4e45 531a", string.Empty, DefaultMimeType, DetectedMimeType.Nes),
            new Fingerprint("7573 7461 7200 3030", string.Empty, "application/x-tar", DetectedMimeType.Tar),
            new Fingerprint("7573 7461 7220 2000", string.Empty, "application/x-tar", DetectedMimeType.Tar),
            new Fingerprint("746f 7833", string.Empty, DefaultMimeType, DetectedMimeType.Tox),
            new Fingerprint("4d4c 5649", string.Empty, DefaultMimeType, DetectedMimeType.Mlv),
            new Fingerprint("377a bcaf 271c", string.Empty, DefaultMimeType, DetectedMimeType._7z),
            new Fingerprint("1f88", string.Empty, "application/x-tar", DetectedMimeType.TarGz),
            new Fingerprint("fd37 7a58 5a00 00", string.Empty, "application/x-tar", DetectedMimeType.TarXz),
            new Fingerprint("434c 4946", string.Empty, DefaultMimeType, DetectedMimeType.Flif),
            new Fingerprint("1a45 dfa3", string.Empty, DefaultMimeType, DetectedMimeType.Matroska),
            new Fingerprint("4154 2654 4f52 4d", "444a 56", DefaultMimeType, DetectedMimeType.Djvu),
            new Fingerprint("774f 4646", string.Empty, "application/font-woff", DetectedMimeType.Woff),
            new Fingerprint("774f 4632", string.Empty, "application/font-woff", DetectedMimeType.Woff2),
            new Fingerprint("3c3f 786d 6c20", string.Empty, "application/xml", DetectedMimeType.Xml),
            new Fingerprint("0061 736d", string.Empty, DefaultMimeType, DetectedMimeType.Wasm),
            new Fingerprint("4357 53", string.Empty, DefaultMimeType, DetectedMimeType.Swf),
            new Fingerprint("4657 53", string.Empty, DefaultMimeType, DetectedMimeType.Swf),
            new Fingerprint("213c 6172 6368 3e", string.Empty, DefaultMimeType, DetectedMimeType.Deb),
            new Fingerprint("5249 4646", "5745 4250", DefaultMimeType, DetectedMimeType.Webp),
            new Fingerprint("7b5c 7274 6631", string.Empty, DefaultMimeType, DetectedMimeType.Rtf),
            new Fingerprint("7801", string.Empty, DefaultMimeType, DetectedMimeType.Zlib),
            new Fingerprint("789c", string.Empty, DefaultMimeType, DetectedMimeType.Zlib),
            new Fingerprint("78da", string.Empty, DefaultMimeType, DetectedMimeType.Zlib),
        };
    }
}